// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerado desde la carpeta docs/: intro + una categoría por proyecto.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
